version: "3.8"
services:
  web:
    image: ghcr.io/pabloreyes093/examen_dev_ops:reyes-3.0.0
    ports:
      - "5000:5000"
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
