name: CD - deploy to VPS

on:
  push:
    branches:
      - reyes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            set -e

            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

            # Crear stack file
            cat > reyes.yml <<'EOF'
version: "3.8"
services:
  web:
    image: ghcr.io/pabloreyes093/examen_dev_ops:reyes-3.0.0
    ports:
      - "1002:5000"
    restart: always
EOF

            docker pull ghcr.io/pabloreyes093/examen_dev_ops:reyes-3.0.0

            # Levantar contenedor
            docker compose -f reyes.yml up -d

            echo "Aplicación desplegada correctamente"
